accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    # path('hello_world/', hello_world, name='hello_world'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),  # 추가
    path('logout/', LogoutView.as_view(), name='logout'),  # 추가
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

mypinterest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from articleapp.views import ArticleListView

urlpatterns = [
    path("", ArticleListView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accountapp.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("comments/", include("commentapp.urls")),
    path("project/", include("projectapp.urls")),
    path("subscribe/", include("subscribeapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
# pragmatic/profileapp/urls.py
from django.urls  import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

articleapp/models.py
# articleapp/models.py
from django.contrib.auth.models import User
from django.db import models
from projectapp.models import Project

# Create your models here.

class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)

    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True)

accountapp/forms.py
# pragmatic/accountapp/forms.py

from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True
        # 필드로 가지고 있는 값들 중에 username 을 disabled 라는 속성을 활성화
        # 만약 바로 위 self.fields 코드가 없다면
        # 우리가 import 한 UserCreationForm 과 그걸 상속받은 AccountUpdateForm은 똑겉은 form 이 됨
        # 이 한줄이 추가 됨 으로써 초기화 이후에 username 의 칸을 비활성화 시켜줌

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.list import MultipleObjectMixin
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.models import User
from accountapp.forms import AccountUpdateForm
from accountapp.decorators import account_ownership_required
from articleapp.models import Article

has_ownership = [account_ownership_required, login_required]

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    paginate_by = 10

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)

@method_decorator(has_ownership,'get') # has_ownership 이라는 배열 내에 있는
@method_decorator(has_ownership,'post') # decorator 들을 모두 확인을 하고 체크 해줌.
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm #UserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'accountapp/update.html'

@method_decorator(has_ownership,'get')
@method_decorator(has_ownership,'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align : center; max-width: 500px; margin: 4rem auto;">>
    <div class="mb-4"> <!-- margin bottom 해서 4배 -->
      <h4>SignUp</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">  <!--url 일원화, post 방식 으로 전송 -->
      {% csrf_token %}  <!-- csrf_token 은 항상 들어 가야 하는 것 -->
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
<!--pragmatic/accountapp/templates/accountapp/delete.html-->

{% extends 'base.html' %}

{% block content %}

  <div style="text-align : center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4"> <!-- margin bottom 해서 4배 -->
      <h4>Quit</h4>
    </div>
    <!--url 일원화, pk=user.pk->pk=target_user.pk 으로 수정 post 방식 으로 전송 -->
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
      {% csrf_token %}  <!-- csrf_token 은 항상 들어 가야 하는 것 -->
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html'%}

{% block content %}

  <div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
      <p>
        {{ target_user.date_joined }}
      </p>
      {% if target_user.profile %} <!--(1) profile 있고 -->
      <!--프로필 이미지를 보여주기-->
      <img src="{{ target_user.profile.image.url }}" alt=""
           style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem;">
      <h2 style="font-family: 'NanumSquareB'">
        <!--nickname 보여주기-->
        {{ target_user.profile.nickname }}
          <!-- 추가된 부분 -->
          {% if target_user == user %} <!--(1-1) target_user == user 라면-->
          <!--프로필 수정 페이지로 이동할 수 있도록-->
          <a class="material-icons"
             style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem"
             href="{% url 'profileapp:update' pk=target_user.profile.pk %}" class="material-icons">
            edit
          </a>
          {% endif %}
          <!--------------->
      </h2>
      <!--대화명을 보여주기-->
      <h5 style="margin-bottom: 3rem;">
        {{ target_user.profile.message }}
      </h5>

      {% else %} <!--(2) profile 이 없는데-->
        <!-- 추가된 부분 -->
        {% if target_user == user %} <!-- (2-1) target_user == user 이라면-->
        <!--프로필 생성 페이지로 이동할 수 있도록-->
        <a href="{% url 'profileapp:create' %}">
          <h2 style="font-family: 'NanumSquareB'">
            Create Profile
          </h2>
        </a>
        <!-- (2-2) 단순히 프로필만 없다면-->
        {% else %}
        <h2>
          닉네임 미설정 <!--다음 출력-->
        </h2>
        {% endif %}
        <!--------------->

      {% endif %}

      {% if target_user == user %}
      <a class="material-icons"
         style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem"
         href="{% url 'accountapp:update' pk=user.pk%}">
        settings
      </a>
      <a class="material-icons"
         style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem"
         href="{% url 'accountapp:delete' pk=user.pk%}">
        cancel
      </a>
      {% endif %}

      {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>
  </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %} <!-- extends 를 이용하여 base 가져오기 -->
{% load bootstrap4 %}

{% block content %}

<div style="text-align: center">
  <div>
    <h4>Login</h4>
  </div>
  <div style="text-align: center; max-width: 500px; margin: 4rem auto; ">
    <form action="{% url 'accountapp:login' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>
</div>

{% endblock%}

accountapp/templates/accountapp/update.html
<!--pragmatic/accountapp/templates/accountapp/update.html-->
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align : center; max-width: 500px; margin: 4rem auto;">>
    <div class="mb-4"> <!-- margin bottom 해서 4배 -->
      <h4>Chang Info</h4>
    </div>
    <!--url 일원화, pk=user.pk->pk=target_user.pk 으로 수정 post 방식 으로 전송 -->
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
      {% csrf_token %}  <!-- csrf_token 은 항상 들어 가야 하는 것 -->
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}