accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    # path('hello_world/', hello_world, name='hello_world'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),  # 추가
    path('logout/', LogoutView.as_view(), name='logout'),  # 추가
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
# articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

mypinterest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from articleapp.views import ArticleListView

urlpatterns = [
    path("", ArticleListView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accountapp.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("comments/", include("commentapp.urls")),
    path("project/", include("projectapp.urls")),
    path("subscribe/", include("subscribeapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
# articleapp/models.py
from django.contrib.auth.models import User
from django.db import models
from projectapp.models import Project

# Create your models here.

class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)

    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True)

templates/snippets/card.html
<div>
    <img src="{{ article.image.url }}" alt="">
</div>

templates/snippets/card_project.html
<div style="display: block; text-align: center;">
  <img src="{{ project.image.url }}" alt="">
  <h5 class="mt-2">
    {{ project.title | truncatechars:8 }} <!-- 8자 넘어가면 .. 처리 -->
  </h5>
</div>

templates/snippets/list_fragment.html
<!--{% load static %}-->
<!-- list_fragment.html 불러지나.-->

{% if article_list %}
    <div class="container">
        {% for article in article_list %}
            <a href=" {% url 'articleapp:detail' pk=article.pk %}">
            {% include 'snippets/card.html' with article=article %}
            </a>
        {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script> <!--js 를 컨테이너 내부로 이동시키기-->

    {% include 'snippets/pagination.html' with page_obj=page_obj %}

{% else %}
    <div class="text-center">
        <h1>No Articles YET! </h1>
    </div>
{% endif %}

<div style="text-align: center">
    <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded_pill mt-3 mb-3 px-3">
        Create Article
    </a>
</div>

templates/snippets/pagination.html
<!-- /pragmatic/templates/snippets/pagination.html 수정-->
<!-- {% url 'articleapp:list' %} 부분을 제거하여 모든 app 에서 사용 가능하도록 -->
<!-- 어떤 페이지에서든 pagination 을 불러오더라도 슬래시(/) 앞에 있는 url 은 그대로 있고 get 파라미터만 바뀌어서 온다.-->

<div style="text-align: center; margin: 1rem 0;">
  {% if page_obj.has_previous %} <!--현재 페이지 page_obj 객체가 이전 페이지를 가지고 있다면-->
  <!--get 방식으로 이전 페이지의 번호를 넘겨주면서 이전 페이지로 넘어가는 링크를 만들어줌-->
  <a href="?page={{ page_obj.previous_page_number }}"
    class="btn btn-secondary rounded-pill">
      {{ page_obj.previous_page_number }}
  </a>
  {% endif %}
  <!-- 현재 있는 페이지 -->
  <a href="?page={{ page_obj.number }}"
    class="btn btn-secondary rounded-pill active">
      {{ page_obj.number }}
  </a>
  {% if page_obj.has_next %} <!-- 다음 페이지가 있다면 -->
  <!-- 다음페이지로 향하는 링크 만들어주기-->
  <a href="?page={{ page_obj.next_page_number }}"
    class="btn btn-secondary rounded-pill active">
      {{ page_obj.next_page_number }}
  </a>
  {% endif %}
</div>