accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    # path('hello_world/', hello_world, name='hello_world'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),  # 추가
    path('logout/', LogoutView.as_view(), name='logout'),  # 추가
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

mypinterest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from articleapp.views import ArticleListView

urlpatterns = [
    path("", ArticleListView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accountapp.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("comments/", include("commentapp.urls")),
    path("project/", include("projectapp.urls")),
    path("subscribe/", include("subscribeapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

articleapp/models.py
# articleapp/models.py
from django.contrib.auth.models import User
from django.db import models
from projectapp.models import Project

# Create your models here.

class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)

    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True)

projectapp/models.py
from django.db import models


class Project(models.Model):
    image = models.ImageField(upload_to='project/', null=True)
    title = models.CharField(max_length=20, null=False)
    description = models.CharField(max_length=200, null=True)

    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.pk} : {self.title}'

projectapp/forms.py
from django.forms import ModelForm

from projectapp.models import Project

class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'image'] # ModelForm 을 기반으로 3가지를 입력으로 받는다

projectapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project


# Create your views here.
from subscribeapp.models import Subscription


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'projectapp/create.html'

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk': self.object.pk})

class ProjectDetailView(DetailView, MultipleObjectMixin):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        project = self.object   # object : 현재 project 페이지
        user = self.request.user

        # 유저가 로그인을 했는지 안했는지 확인
        if user.is_authenticated: # 유저가 접속이 되있다면, usr 와 project 가 각각 user, project 인 구독정보를 찾고
            subscription = Subscription.objects.filter(user=user, project=project)
        # 유저가 접속되어있지 않는다면 구독 버튼 자체가 없기 떄문에 else 구문은 생략
        else:
            subscription = None

        object_list = Article.objects.filter(project=self.get_object())
        # 최종적으로 템플릿으로 넘어갈때는 context_data 안에다가 구독 정보를 우리가 찾은 'subsriptiom' 으로 대체
        # 이런식으로 구독 정보가 있는지 없는지 확인
        return super(ProjectDetailView, self).get_context_data(object_list=object_list,
                                                               subscription=subscription,
                                                               **kwargs)
class ProjectListView(ListView):
    model = Project
    context_object_name = 'project_list'
    template_name = 'projectapp/list.html'
    paginate_by = 5

projectapp/templates/projectapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align : center; max-width: 500px; margin: 4rem auto;">>
    <div class="mb-4"> <!-- margin bottom 해서 4배 -->
      <h4>Create Project</h4>
    </div>
    <!--url 일원화, post 방식 으로 전송 -->
    <form action="{% url 'projectapp:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}  <!-- csrf_token 은 항상 들어 가야 하는 것 -->
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

projectapp/templates/projectapp/detail.html
<!-- /projectapp/templates/projectapp/detail.html -->
{% extends 'base.html' %}

{% block content %}

  <div>
    <!-- 프로젝트 상세정볼 보여주는 부분 -->
    <div style="text-align: center; max-width: 500px; margin: 4rem auto 1.5rem auto;"> <!-- margin 4개로 나눠 쓰기 (위오아왼) -->
      <img src="{{ target_project.image.url }}" alt=""
      style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;">
      <h2 style="font-family: 'NanumSquareB'">
        {{ target_project.title }}
      </h2>
      <h5>
        {{ target_project.description}}
      </h5>
    </div>

    <!-- 구독 버튼 -->
    <div class="text-center mb-5"> <!-- mb-5 : margin-bottom -->
      {% if user.is_authenticated %}
        {% if not subscription %} <!-- 구독이 아닐떄 구독 버튼을 보여주기-->
        <a href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}"
           class="btn btn-primary rounded-pill px-3">   <!-- 버튼 스타일 바꾸기-->
          Subscribe
        </a>
        {% else %} <!-- 구독이 아닐때, 구독 취소 버튼-->
        <a href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}"
           class="btn btn-dark rounded-pill px-3">   <!-- 버튼 스타일 바꾸기-->
          Unsubscribe
        </a>
        {% endif %}
      {% endif %}
    </div>

    <!-- 게시글 보여주기 부분 -->
    </div>
      {% include 'snippets/list_fragment.html' with article_list=object_list %}
    <div>


  </div>

{% endblock %}

projectapp/templates/projectapp/list.html
<!-- /projectapp/templates/list.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>
    .container {
        padding: 0
        margin: 0, auto;
    }

    .container a {
      width: 45%;
      max-width: 250px;
    }

    .container div {
      display: flex;
      justify-content: center;
      align-items: center;
      border-radius: 1rem;
    }

    .container img {
        width: 7rem;
        height: 7rem;
        border-radius: 1rem;
        object-fit: cover;
    }

</style>
    {% if project_list %}
    <div class="container">
        {% for project in project_list %}
        <a href=" {% url 'projectapp:detail' pk=project.pk %}">
            {% include 'snippets/card_project.html' with project=project %}
        </a>
        {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script> <!--js 를 컨테이너 내부로 이동시키기-->
    {% else %}
    <div class="text-center">
        <h1>No Projects YET! </h1>
    </div>
    {% endif %}

    {% include 'snippets/pagination.html' with page_obj=page_obj %}

    <div style="text-align: center;">
        <a href="{% url 'projectapp:create' %}" class="btn btn-dark rounded-pill mt-3 mb-3 px-3">
            Create Project
        </a>
    </div>

{% endblock %}